"""The SKU the platform stored is not always the SKU we sent.

On 2026-08-03 a batch of GTV products was created with the SKU rounded to
6 significant figures - 198651491114 became 198651000000, 823830288833
became 823830000000. 641 listings landed that way: live, in stock, most
of them winning the Buy Box, and every one of them invisible to our
automation, because we address listings by the SKU we hold and the
platform answers "SKU does not exist" for it. Sold-out items could not be
zeroed, prices could not be corrected, and the Buy Box defense could not
see them. OnBuy's seller support could not find them either (2026-09-02),
for the same reason - they searched the SKU we quoted.

Proven addressable under the stored SKU on 2026-09-03 (run 33732126122):
PUT /v2/listings/by-sku returned 200 with real product_listing_ids for
the rounded form. So this module translates at the boundary - outbound
writes go to the SKU the platform holds, inbound listings come back under
the SKU we hold - and the rest of the pipeline keeps working in true
SKUs, which is what the sheet, the mirror and the supplier links use.

sku_aliases.csv is regenerated by probe_sku_rounding.py. A pair is only
usable when it is unambiguous in BOTH directions; where two of our SKUs
round onto one listing (4 of them do) no alias is recorded, because a
write would otherwise hit whichever product won the collision. Those stay
unaddressable until the platform corrects the SKUs.

This is a bridge, not a cure: the listings should be corrected at source.

2026-09-04: OnBuy corrected them at source - the wrong-SKU listings were
removed and re-added against the same products under our real SKUs, with
price/stock/settings carried over (support, ticket reply). The re-probe
confirmed 7,707 sheet SKUs now answer exactly and only the 4 collision
OPCs remain, which by the ambiguity rule were never aliased - so the data
file is empty and this module is a deliberate no-op until a corruption
ever appears again (regenerate via probe_sku_rounding.yml).
"""
import csv
import io
import os
from collections import Counter

ALIAS_FILE = os.getenv("SKU_ALIAS_FILE") or os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "sku_aliases.csv")


def load_aliases(path=None):
    """(true -> stored, stored -> true). Ambiguous pairs on either side are
    dropped rather than guessed - see the module docstring."""
    path = path or ALIAS_FILE
    pairs = []
    try:
        with io.open(path, encoding="utf-8-sig") as fh:
            for row in csv.DictReader(fh):
                true_sku = str(row.get("true_sku") or "").strip()
                onbuy_sku = str(row.get("onbuy_sku") or "").strip()
                if true_sku and onbuy_sku and true_sku != onbuy_sku:
                    pairs.append((true_sku, onbuy_sku))
    except FileNotFoundError:
        return {}, {}
    lhs = Counter(t for t, _ in pairs)
    rhs = Counter(o for _, o in pairs)
    forward = {t: o for t, o in pairs if lhs[t] == 1 and rhs[o] == 1}
    return forward, {o: t for t, o in forward.items()}


TO_ONBUY, TO_TRUE = load_aliases()


def to_onbuy(sku):
    """The SKU to put on the wire for this row's listing."""
    s = str(sku or "").strip()
    return TO_ONBUY.get(s, s)


def to_true(sku):
    """The SKU the sheet knows, given whatever the API just returned."""
    s = str(sku or "").strip()
    return TO_TRUE.get(s, s)


def describe():
    return f"{len(TO_ONBUY)} SKU alias(es) loaded from {os.path.basename(ALIAS_FILE)}"
